### ISSUE TITLE
tag

### ISSUE THREAD

**Issue by rene-d** [PierreGagelin/aor-2022#1]
il manque le tag advent-of-code (et éventuellement advent-of-code-<année>) pour encore améliorer les stats 

![image](https://user-images.githubusercontent.com/10288093/211207743-a4dc96b2-f687-4698-9119-fb5dc8ae81c5.png)

**Comment by PierreGagelin** [comment]
Je ne vois pas où tu peux faire ça ?

**Comment by rene-d** [comment]
c'est dans la "roue crantée" à droite de About, sur la page d'accueil du projet.

ajoute les topics qui vont bien

**Comment by PierreGagelin** [comment]
Ah yes, merci ! J'avais jamais vu ce truc de paramétrage :sweat_smile:

Tu penses qu'il faut mettre "advent-of-code" et "advent-of-code-2022" ou tu penses qu'il y a une mise en relation automatique ? J'ai aussi ajouté la catégorie "rust" et "puzzle-solution"

**Comment by PierreGagelin** [comment]
J'ai mis les deux, je pense que c'est réglé ! De toutes façons je vais migrer sur GitLab alors ce dépôt va disparaître :stuck_out_tongue_closed_eyes:
